# Generated by Django 5.2 on 2025-04-03 12:40

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('accountname', models.CharField(max_length=100)),
                ('accountemailid', models.EmailField(max_length=254)),
                ('accountphone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('accountpan', models.CharField(max_length=10)),
                ('accountgst', models.CharField(max_length=15)),
                ('userid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('transactionname', models.CharField(max_length=100)),
                ('transactionemailid', models.EmailField(max_length=254)),
                ('transactionphone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('transactionamount', models.FloatField()),
                ('transactioncreatedate', models.DateField()),
                ('transactionduedate', models.DateField()),
                ('userid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
